version: '3.8'

services:
    nginx:
      image: nginx
      container_name: ngx
      ports:
            - 80:80
      depends_on:
        - backend
        - frontend
      networks:
        - front-back-ngx-network
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf

    redis:
      image: redis
      container_name: redis
      restart: unless-stopped
      volumes:
        - rd:/usr/src/redis/files
      ports:
        - 6379:6379
      command: ["redis-server"]

    postgres:
      image: postgres
      container_name: postgres
      restart: unless-stopped
      environment:
        - POSTGRES_HOST=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DATABASE=postgres
      volumes:
        - database:/var/lib/postgresql/data

    backend:
      container_name: backend
      build: ./backend
      environment:
        - REDIS_HOST=redis
        - POSTGRES_HOST=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DATABASE=postgres
        - REQUEST_ORIGIN=http://localhost:80
      depends_on:
        - redis
        - postgres
      networks:
        - front-back-ngx-network

    frontend:
      container_name: frontend
      build: ./frontend
      environment:
        - REACT_APP_BACKEND_URL=http://localhost:80
      networks:
        - front-back-ngx-network

volumes:
  nginx.conf:
  rd:
  database:

networks:
  front-back-ngx-network:
    name: front-back-ngx-network
