version: '3.8'

services:
    backend:
      container_name: backend
      build: ./backend
      ports:
        - 8080:8080

    frontend:
      container_name: frontend
      build: ./frontend
      ports:
        - 5000:5000
