version: '3.8'

services:
    redis:
      image: redis
      container_name: redis
      restart: unless-stopped
      command: ["redis-server"]

    backend:
      container_name: backend
      build: ./backend
      environment:
        REDIS_HOST: redis
      ports:
        - 8080:8080

    frontend:
      container_name: frontend
      build: ./frontend
      ports:
        - 5000:5000
