version: '3.8'

services:
    redis:
      image: redis
      container_name: red
      restart: unless-stopped
      volumes:
        - rd:/usr/src/redis/files
      command: ["redis-server"]

    db:
      image: postgres:13.2-alpine
      restart: unless-stopped
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      container_name: db_redmine
      volumes:
        - database:/var/lib/postgresql/data

    backend:
      container_name: backend
      build: ./backend
      environment:
        - REDIS_HOST=red
        - POSTGRES_HOST=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DATABASE=postgres
      ports:
        - 8080:8080
      depends_on:
        - redis
        - db

volumes: 
  rd:
  database: