version: '3.8'

services:
    frontend:
      container_name: frontend
      build: ./frontend
      ports:
        - 3000:5000
      depends_on:
        - backend

    backend:
      container_name: backend
      build: ./backend
      ports:
        - 5000:5000
      volumes:
        - model:/src/model
      depends_on:
        - training

    training:
      container_name: training
      build: ./training
      volumes:
        - model:/src/model
        - images:/src/imgs
        #- data:/src/data

volumes: 
  model:
  images:
  #data: